### ISSUE TITLE
Editors and graphs?

### ISSUE THREAD

**Issue by MihaMarkic** [praeclarum/ImmutableUI#3]
How do you handle input editor? Like Entry.
Also rebuilding entire page each time something changes seems like an overkill. Is there a graph compare which applies only actually changed properties (think react)?

**Comment by praeclarum** [comment]
Yeah sorry in the readme I mentioned I haven't bound events yet. They will become just additional properties.

The whole point of this library is that it **does not* rebuild the tree every time. It's like React! The Apply functions are incremental.

In adding to that, I plan on adding even more state diffing in future versions.

**Comment by MihaMarkic** [comment]
Rect-ish is good. However, the diffing and small details might complicate it quite a bit.  That said I'm really curious where this will end and if I can use my sharp-redux with it :)
I actually toyed with react approach to wpf but left it half baked.
